### ISSUE TITLE
Renomear repositório

### ISSUE THREAD

**Issue by rodorgas** [bccnotes/bccnotes#1]
Acho que não faz muito sentido dividir as notas em repositórios de acordo com o semestre em que elas foram feitas. Sugiro renomear para `bccnotes`. A organização também poderia ter esse nome, IMO.

**Comment by Leandrigues** [comment]
Muito obrigado pela genial ideia, consertado!!!

**Comment by rodorgas** [comment]
E a organização, não vai mudar?

**Comment by Leandrigues** [comment]
Sugiro prestar mais atenção, pois já mudei.

**Comment by rodorgas** [comment]
Desculpe a desatenção e obrigado!
